---
- name: Playbook for vagrant+kube
  hosts: all
  gather_facts: true

  tasks:
   - name: Install kvm2
     ansible.builtin.dnf:
      name:
       - vagrant
       - vagrant-libvirt
       - ansible
      state: installed
     notify: virtnetwork
     become: true

   - name: Force all notified handler to run at this point, not waiting for normal sync points
     ansible.builtin.meta: flush_handlers

  handlers:
   - name: Virtnetwork
     ansible.builtin.systemd:
      name: virtnetworkd
      enabled: true
      state: restarted
     become: true
