---
- name: Playbook for kube master node
  hosts: all
  gather_facts: true
  become: true

  tasks:
  - name: Initialize Kube cluster
    ansible.builtin.command:
      cmd: kubeadm init --ignore-preflight-errors=NumCPU # setting up on a single core host
    register: kube_results

  - name: Setup kubeconfig for vagrant user
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ ansible_env.PWD }}.kube/config"
      group: "{{ ansible_user_gid}}"
      owner: "{{ ansible_user_id}}"
      remote_src: true
    become: false  