---
  - name: Is worker configured
    ansible.builtin.stat:
      path: /etc/kubernetes/kubelet.conf 
    register: kubelet_conf

  - name: Join Cluster
    block:  
    - name: Generate join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: join_command
      delegate_to: master

    - name: attach worker kube node
      ansible.builtin.command:
        cmd: "{{ join_command.stdout }}"
      register: worker_results
    when: not kubelet_conf.stat.exists

